export type ChibanData = {
  /// 全国地方公共団体コード
  lg_code: string
  /// 町字ID
  machiaza_id: string
  /// 地番ID
  prc_id: string
  /// 市区町村名
  city: string
  /// 政令市区名
  ward: string
  /// 大字・町名
  oaza_cho: string
  /// 丁目名
  chome: string
  /// 小字名
  koaza: string
  /// 地番1
  prc_num1: string
  /// 地番2
  prc_num2: string
  /// 地番3
  prc_num3: string
  /// 住居表示フラグ
  rsdt_addr_flg: string
  /// 地番レコード区分フラグ
  prc_rec_flg: string
  /// 地番区域コード
  prc_area_code: string
  /// 効力発生日
  efct_date: string
  /// 廃止日
  ablt_date: string
  /// 原典資料コード
  src_code: string
  /// 備考
  remarks: string
  /// 不動産番号
  real_prop_num: string
};

export type ChibanPosData = {
  /// 全国地方公共団体コード
  lg_code: string;
  /// 町字ID
  machiaza_id: string;
  /// 地番ID
  prc_id: string;
  /// 代表点_経度
  rep_lon: string;
  /// 代表点_緯度
  rep_lat: string;
  /// 代表点_座標参照系
  rep_srid: string;
  /// 代表点_地図情報レベル
  rep_scale: string;
  /// 代表点_原典資料コード
  rep_src_code: string;
  /// ポリゴン_ファイル名
  plygn_fname: string;
  /// ポリゴン_キーコード
  plygn_kcode: string;
  /// ポリゴン_データフォーマット
  plygn_fmt: string;
  /// ポリゴン_座標参照系
  plygn_srid: string;
  /// ポリゴン_地図情報レベル
  plygn_scale: string;
  /// ポリゴン_原典資料コード
  plygn_src_code: string;
  /// 法務省地図_市区町村コード
  moj_map_city_code: string;
  /// 法務省地図_大字コード
  moj_map_oaza_code: string;
  /// 法務省地図_丁目コード
  moj_map_chome_code: string;
  /// 法務省地図_小字コード
  moj_map_koaza_code: string;
  /// 法務省地図_予備コード
  moj_map_spare_code: string;
  /// 法務省地図_筆id
  moj_map_brushid: string;
};
